### ISSUE TITLE
Crash after inkspace is closed

### ISSUE THREAD

**Issue by Tchekda** [oxplot/pdfrankenstein#13]
Hi,
After saving the file and closing inkspace, i'm getting the crash log : 
```
Jun 08 01:09:08 hspecter xsession[295672]: [xcb] Unknown sequence number while awaiting reply
Jun 08 01:09:08 hspecter xsession[295672]: [xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
Jun 08 01:09:08 hspecter xsession[295672]: [xcb] Aborting, sorry about that.
Jun 08 01:09:08 hspecter xsession[295672]: pdfrankenstein: xcb_io.c:365: poll_for_response: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Jun 08 01:09:08 hspecter xsession[295672]: SIGABRT: abort
Jun 08 01:09:08 hspecter xsession[295672]: PC=0x7f73b3689c1f m=0 sigcode=18446744073709551610
Jun 08 01:09:08 hspecter xsession[295672]: signal arrived during cgo execution
Jun 08 01:09:08 hspecter xsession[295672]: goroutine 1 [syscall]:
Jun 08 01:09:08 hspecter xsession[295672]: runtime.cgocall(0x8680a0, 0xc0000d3ef0)
Jun 08 01:09:08 hspecter xsession[295672]:         runtime/cgocall.go:157 +0x5c fp=0xc0000d3ec8 sp=0xc0000d3e90 pc=0x490c5c
Jun 08 01:09:08 hspecter xsession[295672]: github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
Jun 08 01:09:08 hspecter xsession[295672]:         _cgo_gotypes.go:17424 +0x45 fp=0xc0000d3ef0 sp=0xc0000d3ec8 pc=0x60ff85
Jun 08 01:09:08 hspecter xsession[295672]: github.com/gotk3/gotk3/gtk.Main(...)
Jun 08 01:09:08 hspecter xsession[295672]:         github.com/gotk3/gotk3@v0.6.1/gtk/gtk.go:1241
Jun 08 01:09:08 hspecter xsession[295672]: main.run()
Jun 08 01:09:08 hspecter xsession[295672]:         github.com/oxplot/pdfrankenstein/main.go:561 +0x8c fp=0xc0000d3f38 sp=0xc0000d3ef0 pc=0x85878c
Jun 08 01:09:08 hspecter xsession[295672]: main.main()
Jun 08 01:09:08 hspecter xsession[295672]:         github.com/oxplot/pdfrankenstein/main.go:568 +0x70 fp=0xc0000d3f80 sp=0xc0000d3f38 pc=0x858830
Jun 08 01:09:08 hspecter xsession[295672]: runtime.main()
Jun 08 01:09:08 hspecter xsession[295672]:         runtime/proc.go:250 +0x212 fp=0xc0000d3fe0 sp=0xc0000d3f80 pc=0x4c30d2
Jun 08 01:09:08 hspecter xsession[295672]: runtime.goexit()
Jun 08 01:09:08 hspecter xsession[295672]:         runtime/asm_amd64.s:1571 +0x1 fp=0xc0000d3fe8 sp=0xc0000d3fe0 pc=0x4ef081
Jun 08 01:09:08 hspecter xsession[295672]: rax    0x0
Jun 08 01:09:08 hspecter xsession[295672]: rbx    0x482f8
Jun 08 01:09:08 hspecter xsession[295672]: rcx    0x7f73b3689c1f
Jun 08 01:09:08 hspecter xsession[295672]: rdx    0x6
Jun 08 01:09:08 hspecter xsession[295672]: rdi    0x482f8
Jun 08 01:09:08 hspecter xsession[295672]: rsi    0x482f8
Jun 08 01:09:08 hspecter xsession[295672]: rbp    0x7f73b37b3268
Jun 08 01:09:08 hspecter xsession[295672]: rsp    0x7fff2b390480
Jun 08 01:09:08 hspecter xsession[295672]: r8     0x7
Jun 08 01:09:08 hspecter xsession[295672]: r9     0x26018c0
Jun 08 01:09:08 hspecter xsession[295672]: r10    0x8
Jun 08 01:09:08 hspecter xsession[295672]: r11    0x246
Jun 08 01:09:08 hspecter xsession[295672]: r12    0x7f73b3362c13
Jun 08 01:09:08 hspecter xsession[295672]: r13    0x16d
Jun 08 01:09:08 hspecter xsession[295672]: r14    0x6
Jun 08 01:09:08 hspecter xsession[295672]: r15    0x7fff2b390798
Jun 08 01:09:08 hspecter xsession[295672]: rip    0x7f73b3689c1f
Jun 08 01:09:08 hspecter xsession[295672]: rflags 0x246
Jun 08 01:09:08 hspecter xsession[295672]: cs     0x33
Jun 08 01:09:08 hspecter xsession[295672]: fs     0x0
Jun 08 01:09:08 hspecter xsession[295672]: gs     0x0
```

**Comment by oxplot** [comment]
I think I know what the issue is. Can you try a new release I just pushed to see if that fixes it: https://github.com/oxplot/pdfrankenstein/releases/tag/v0.9.1

**Comment by oxplot** [comment]
Probably related: https://github.com/oxplot/pdfrankenstein/issues/10

**Comment by Tchekda** [comment]
Worked, thank you very much. 
Will be committing the package to NixOS soon
